# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-16 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20181009_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Category')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Tag')),
            ],
        ),
    ]
