# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-22 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20181020_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('local_idf', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='questions_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='global_idf',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='questions_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='globalcounter',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Category'),
        ),
        migrations.AddField(
            model_name='globalcounter',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Tag'),
        ),
    ]
