# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_auto_20181022_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
