# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_auto_20181024_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='questions',
            field=models.ManyToManyField(related_name='tags', to='analytics.Question'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.TextField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='counter',
            index=models.Index(fields=['-datetime'], name='analytics_c_datetim_b1d869_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-created_at'], name='analytics_q_created_1466a6_idx'),
        ),
    ]
